$ANSIBLE_VAULT;1.1;AES256
63326265643261393130323538313431326262346433383862336437666161653136333834376333
3864623739376662363465393762396430306330383335370a666462666132353739323964616166
37383230306435646461386666383264383039343032643733623835656165326231313463336239
3031313532646635640a393835383362326434636431653063346664343830323934373630326430
38646134336435616263643632306664623330643033313133313630663434663664656631343534
35313132376133356133316230326261643031646364336362623230633933643333623937313262
326332623936653130356635383333376434
